name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate to GCP
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Deploy to App Engine
      - name: Deploy to GCP App Engine
        uses: uses: 'google-github-actions/deploy-appengine@v2'
